Arjun Features

In [2]:
import pandas as pd

amazon = pd.read_csv(r"C:\project\CartIQ\data_raw\amazon.csv")
flipkart = pd.read_csv(r"C:\project\CartIQ\data_raw\flipkart_com-ecommerce_sample.csv")
myntra=pd.read_csv(r"C:\project\CartIQ\data_raw\Myntra.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\project\\CartIQ\\data_raw\\amazon.csv'

In [ ]:
print(amazon.head())

print(amazon.shape)

print(amazon.columns)

print(amazon.info())

print(amazon.isnull().sum())

print(amazon.duplicated().sum())

In [ ]:
print("FLIPKART DATASET")
print(flipkart.head())
print(flipkart.shape)
print(flipkart.columns)
print(flipkart.info())
print(flipkart.isnull().sum())
print("Duplicates:", flipkart.duplicated().sum())

In [ ]:
print("Myntra DATASET")
print(myntra.head())
print(myntra.shape)
print(myntra.columns)
print(myntra.info())
print(myntra.isnull().sum())
print("Duplicates:", myntra.duplicated().sum())

Vivek features

In [29]:
import pandas as pd

# load datasets
amazon = pd.read_csv("../data_raw/amazon.csv")
flipkart = pd.read_csv("../data_raw/flipkart.csv")

In [30]:
amazon.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [31]:
amazon.shape

(1465, 16)

In [32]:
amazon.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [33]:
amazon.dtypes

product_id             str
product_name           str
category               str
discounted_price       str
actual_price           str
discount_percentage    str
rating                 str
rating_count           str
about_product          str
user_id                str
user_name              str
review_id              str
review_title           str
review_content         str
img_link               str
product_link           str
dtype: object

In [37]:
amazon.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 183.3 KB

In [41]:
amazon.describe()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B07JW9H4J1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

In [43]:
amazon.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [45]:
amazon.duplicated().sum()

np.int64(0)

In [47]:
amazon["category"].unique()

<StringArray>
[                                      'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
                                             'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters',
                                                          'Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables',
                                                           'Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions',
                                                             'Electronics|HomeTheater,TV&Video|Accessories|RemoteControls',
                                                        'Electronics|HomeTheater,TV&Video|Televisions|StandardTelevisions',
                            'Electronics|HomeTheater,TV&Video|Accessories|TVMounts,Stands&Turntables|TVWall&CeilingMounts',
                                                           'Electronics|HomeTheater,TV&Video|Accessories|Cables|RCACables',
                                                             'Electronics|HomeAudio|Accessories|SpeakerAccessories|Mounts',
                                                       'Electronics|HomeTheater,TV&Video|Accessories|Cables|OpticalCables',
 ...
                              'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|SmallApplianceParts&Accessories',
                                           'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons',
                                            'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|StovetopEspressoPots',
                          'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeeMakerAccessories|MeasuringSpoons',
                                                   'Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea&Espresso|CoffeePresses',
                                                   'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers',
                                          'Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories',
                                                  'Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers',
                                                               'Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans',
 'Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags']
Length: 211, dtype: str

In [49]:
flipkart.head()
flipkart.tail()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
19995,7179d2f6c4ad50a17d014ca1d2815156,2015-12-01 10:15:43 +0000,http://www.flipkart.com/walldesign-small-vinyl...,WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7KFJAKSTDY9G,1500.0,730.0,"[""http://img6a.flixcart.com/image/wall-decorat...",False,Buy WallDesign Small Vinyl Sticker for Rs.730 ...,No rating available,No rating available,WallDesign,"{""product_specification""=>[{""key""=>""Number of ..."
19996,71ac419198359d37b8fe5e3fffdfee09,2015-12-01 10:15:43 +0000,http://www.flipkart.com/wallmantra-large-vinyl...,Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE9F5URNQGJCGH,1429.0,1143.0,"[""http://img6a.flixcart.com/image/sticker/z/g/...",False,Buy Wallmantra Large Vinyl Stickers Sticker fo...,No rating available,No rating available,Wallmantra,"{""product_specification""=>[{""key""=>""Number of ..."
19997,93e9d343837400ce0d7980874ece471c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE7VAYDKQZEBSD,1299.0,999.0,"[""http://img5a.flixcart.com/image/sticker/b/s/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19998,669e79b8fa5d9ae020841c0c97d5e935,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE8YSVEPPCZ42Y,1499.0,1199.0,"[""http://img5a.flixcart.com/image/sticker/4/2/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."
19999,cb4fa87a874f715fff567f7b7b3be79c,2015-12-01 10:15:43 +0000,http://www.flipkart.com/elite-collection-mediu...,Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",STIE88KN9ZDSGZKY,1499.0,999.0,"[""http://img6a.flixcart.com/image/sticker/z/k/...",False,Buy Elite Collection Medium Acrylic Sticker fo...,No rating available,No rating available,Elite Collection,"{""product_specification""=>[{""key""=>""Number of ..."

In [51]:
flipkart.shape

(20000, 15)

In [53]:
flipkart.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='str')

In [55]:
flipkart.dtypes

uniq_id                        str
crawl_timestamp                str
product_url                    str
product_name                   str
product_category_tree          str
pid                            str
retail_price               float64
discounted_price           float64
image                          str
is_FK_Advantage_product       bool
description                    str
product_rating                 str
overall_rating                 str
brand                          str
product_specifications         str
dtype: object

In [57]:
flipkart.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  str
 1   crawl_timestamp          20000 non-null  str
 2   product_url              20000 non-null  str
 3   product_name             20000 non-null  str
 4   product_category_tree    20000 non-null  str
 5   pid                      20000 non-null  str
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  str
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  str
 11  product_rating           20000 non-null  str
 12  overall_rating           20000 non-null  str
 13  brand                    14136 non-null  str
 14  product_specifications   19986 non-null  str
dtypes: bool(1), float64(2), str(12)
memory usage: 2.2 MB

In [59]:
flipkart.describe()

        retail_price  discounted_price
count   19922.000000      19922.000000
mean     2979.206104       1973.401767
std      9009.639341       7333.586040
min        35.000000         35.000000
25%       666.000000        350.000000
50%      1040.000000        550.000000
75%      1999.000000        999.000000
max    571230.000000     571230.000000

In [61]:
flipkart.isnull().sum()

uniq_id                       0
crawl_timestamp               0
product_url                   0
product_name                  0
product_category_tree         0
pid                           0
retail_price                 78
discounted_price             78
image                         3
is_FK_Advantage_product       0
description                   2
product_rating                0
overall_rating                0
brand                      5864
product_specifications       14
dtype: int64

In [63]:
flipkart["brand"].nunique()

3499

In [65]:
flipkart.duplicated().sum()

np.int64(0)

MYNTRA

In [68]:
import pandas as pd

In [72]:
myntra=pd.read_csv("../data_raw/Myntra.csv")

In [74]:
myntra.head()

,p_id,name,products,price,colour,brand,img,ratingCount,avg_rating,description,p_attributes
0,17048614,Khushal K Women Black Ethnic Motifs Printed Ku...,"Kurta, Palazzos, Dupatta",5099.0,Black,Khushal K,http://assets.myntassets.com/assets/images/170...,4522.0,4.418399,Black printed Kurta with Palazzos with dupatta...,"{'Add-Ons': 'NA', 'Body Shape ID': '443,333,32..."
1,16524740,InWeave Women Orange Solid Kurta with Palazzos...,"Kurta, Palazzos, Floral Print Dupatta",5899.0,Orange,InWeave,http://assets.myntassets.com/assets/images/165...,1081.0,4.119334,Orange solid Kurta with Palazzos with dupatta<...,"{'Add-Ons': 'NA', 'Body Shape ID': '443,333,32..."
2,16331376,Anubhutee Women Navy Blue Ethnic Motifs Embroi...,"Kurta, Trousers, Dupatta",4899.0,Navy Blue,Anubhutee,http://assets.myntassets.com/assets/images/163...,1752.0,4.161530,Navy blue embroidered Kurta with Trousers with...,"{'Add-Ons': 'NA', 'Body Shape ID': '333,424', ..."
3,14709966,Nayo Women Red Floral Printed Kurta With Trous...,"Kurta, Trouser, Dupatta",3699.0,Red,Nayo,http://assets.myntassets.com/assets/images/147...,4113.0,4.088986,Red printed kurta with trouser and dupatta<br>...,"{'Add-Ons': 'NA', 'Body Shape ID': '333,424', ..."
4,11056154,AHIKA Women Black & Green Printed Straight Kurta,Kurta,1350.0,Black,AHIKA,http://assets.myntassets.com/assets/images/110...,21274.0,3.978377,"Black and green printed straight kurta, has a ...","{'Body Shape ID': '424', 'Body or Garment Size..."

In [78]:
myntra.shape

(14214, 11)

In [80]:
myntra.columns

Index(['p_id', 'name', 'products', 'price', 'colour', 'brand', 'img',
       'ratingCount', 'avg_rating', 'description', 'p_attributes'],
      dtype='str')

In [82]:
myntra.dtypes

p_id              int64
name                str
products            str
price           float64
colour              str
brand               str
img                 str
ratingCount     float64
avg_rating      float64
description         str
p_attributes        str
dtype: object

In [84]:
myntra.info()

<class 'pandas.DataFrame'>
RangeIndex: 14214 entries, 0 to 14213
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   p_id          14214 non-null  int64
 1   name          14214 non-null  str
 2   products      14214 non-null  str
 3   price         14214 non-null  float64
 4   colour        14214 non-null  str
 5   brand         14214 non-null  str
 6   img           14214 non-null  str
 7   ratingCount   6530 non-null   float64
 8   avg_rating    6530 non-null   float64
 9   description   14214 non-null  str
 10  p_attributes  14214 non-null  str
dtypes: float64(3), int64(1), str(7)
memory usage: 1.2 MB

In [86]:
myntra.describe()

               p_id         price   ratingCount   avg_rating
count  1.421400e+04  14214.000000   6530.000000  6530.000000
mean   1.569275e+07   2970.434009    184.312251     4.101044
std    3.152415e+06   2570.232988    782.464972     0.475756
min    7.016600e+04    169.000000      1.000000     1.000000
25%    1.415589e+07   1599.000000      9.000000     3.888889
50%    1.638232e+07   2222.000000     23.000000     4.180940
75%    1.807670e+07   3498.000000     80.000000     4.392641
max    1.941576e+07  47999.000000  21274.000000     5.000000

In [88]:
myntra.isnull().sum()

p_id               0
name               0
products           0
price              0
colour             0
brand              0
img                0
ratingCount     7684
avg_rating      7684
description        0
p_attributes       0
dtype: int64

In [90]:
myntra.duplicated().sum()

np.int64(0)

In [94]:
myntra["brand"].nunique()

1022

In [98]:
print(myntra.columns.tolist())
print()
print(myntra.shape)
print()
print(myntra.isnull().sum())

['p_id', 'name', 'products', 'price', 'colour', 'brand', 'img', 'ratingCount', 'avg_rating', 'description', 'p_attributes']

(14214, 11)

p_id               0
name               0
products           0
price              0
colour             0
brand              0
img                0
ratingCount     7684
avg_rating      7684
description        0
p_attributes       0
dtype: int64

In [100]:
print(amazon.columns.tolist())
print()
print(amazon.shape)
print()
print(amazon.isnull().sum())

['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', 'product_link']

(1465, 16)

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [102]:
print(flipkart.columns.tolist())
print()
print(flipkart.shape)
print()
print(flipkart.isnull().sum())

['uniq_id', 'crawl_timestamp', 'product_url', 'product_name', 'product_category_tree', 'pid', 'retail_price', 'discounted_price', 'image', 'is_FK_Advantage_product', 'description', 'product_rating', 'overall_rating', 'brand', 'product_specifications']

(20000, 15)

uniq_id                       0
crawl_timestamp               0
product_url                   0
product_name                  0
product_category_tree         0
pid                           0
retail_price                 78
discounted_price             78
image                         3
is_FK_Advantage_product       0
description                   2
product_rating                0
overall_rating                0
brand                      5864
product_specifications       14
dtype: int64